services:
  - type: web
    name: valhalla-api
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: VALHALLA_MATRIX_KEY
        sync: false  # Set manually in Render dashboard
      - key: ALLOWED_ORIGINS
        value: "*"  # Configure for production
    healthCheckPath: /health
    autoDeploy: true
